enable_audio_bell no
confirm_os_window_close 0
mouse_hide_wait 0

scrollback_lines 10000

font_family Ubuntu Mono Nerd Font
font_size 12.0

cursor_shape block
cursor_blink_interval 0

copy_on_select yes

term xterm-kitty

repaint_delay 10
input_delay 3

linux_display_server auto

allow_remote_control yes

include themes/void-space-kitty.conf
